<a href="https://colab.research.google.com/github/mourouzidou/BLAST_Analysis_Pipeline/blob/main/ai-tac_run.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/smaslova/AI-TAC.git


Cloning into 'AI-TAC'...
remote: Enumerating objects: 123, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 123 (delta 21), reused 15 (delta 15), pack-reused 92 (from 1)
Receiving objects: 100% (123/123), 11.16 MiB | 19.77 MiB/s, done.
Resolving deltas: 100% (55/55), done.


In [3]:
import os
os.chdir('/content/AI-TAC/code')
print("Current working directory:", os.getcwd())


Current working directory: /content/AI-TAC/code


In [42]:
!python -u extract_motifs.py 'aitac' '../sample_data/one_hot_seqs.npy' '../sample_data/cell_type_array.npy' '../sample_data/peak_names.npy'

In [134]:
import numpy as np



one_hot_seqs_path = "../sample_data/one_hot_seqs.npy"

cell_type_array_path = "../sample_data/cell_type_array.npy"

peak_names_path = "../sample_data/peak_names.npy"

predictions = np.load('../outputs/aitac/motifs/predictions.npy')
# print(predictions.shape)
# print("predictions : ", predictions[18])

# Load the data to analyze its structure

try:

    one_hot_seqs = np.load(one_hot_seqs_path)

    cell_type_array = np.load(cell_type_array_path)

    peak_names = np.load(peak_names_path)



    # Display the shapes and examples

    print(f"one_hot_seqs shape: {one_hot_seqs.shape}")  # Shape of one-hot encoded sequences

    print(f"cell_type_array shape: {cell_type_array.shape}")  # Shape of cell type array (labels)

    print(f"peak_names shape: {peak_names.shape}")  # Shape of peak names



    # Display a sample of the data

    print("\nSample of one_hot_seqs (first sequence):", one_hot_seqs[1][:, :])  # First sequence, first 10 bases

    print("\nSample of cell_type_array (first entry):", cell_type_array[18])  # First label

    print("\nSample of peak_names (first entry):", peak_names[1])  # First peak name



except Exception as e:

    print("Error loading sample data:", str(e))


ocr_matrix = np.load('../outputs/aitac/motifs/OCR_matrix.npy')
print(ocr_matrix)


one_hot_seqs shape: (100, 4, 251)
cell_type_array shape: (100, 81)
peak_names shape: (100,)

Sample of one_hot_seqs (first sequence): [[1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 1 0]]

Sample of cell_type_array (first entry): [1.151828 1.605631 1.727072 2.665989 3.523474 1.858122 1.373942 1.101284
 1.692156 1.416678 1.233521 2.4296   1.687405 1.417435 1.373942 1.703204
 1.580527 1.29398  1.086789 1.278626 1.085566 1.635836 1.559985 1.506694
 1.368486 1.17485  1.4463   1.36636  1.093838 1.640876 1.093838 1.52303
 1.090893 1.095567 1.475017 1.465835 1.747995 1.482109 1.090893 1.242042
 1.729853 1.531852 1.192144 1.525959 1.131276 1.708476 1.852317 1.373942
 1.608637 1.21101  1.185716 1.207718 1.667046 1.377415 1.249117 1.543197
 1.249231 1.51819  1.384767 2.146631 1.589669 1.764902 1.31831  1.449058
 1.249117 1.119638 1.240047 1.095567 1.086789 1.123134 1.407541 1.136541
 1.516218 1.743399 1.417632 1.093838 1.500516 1.088865 1.216065 1.192439
 1.43034 ]

Sample

In [156]:
import numpy as np



one_hot_seqs_path = "../one_hot_seqs_pax5.npy"

cell_type_array_path = "../target_heights_Pax5.npy"

peak_names_path = "../peak_names_pax5.npy"

# predictions = np.load('../outputs/aitac/motifs/predictions.npy')


try:

    one_hot_seqs = np.load(one_hot_seqs_path)

    cell_type_array = np.load(cell_type_array_path, allow_pickle=True)

    peak_names = np.load(peak_names_path, allow_pickle=True)



    # Display the shapes and examples

    print(f"one_hot_seqs shape: {one_hot_seqs.shape}")  # Shape of one-hot encoded sequences

    print(f"cell_type_array shape: {cell_type_array.shape}")  # Shape of cell type array (labels)

    print(f"peak_names shape: {peak_names.shape}")  # Shape of peak names



    # Display a sample of the data

    print("\nSample of one_hot_seqs (first sequence):", one_hot_seqs[1][:, :])  # First sequence, first 10 bases

    print("\nSample of cell_type_array (first entry):", cell_type_array[18])  # First label

    print("\nSample of peak_names (first entry):", peak_names[1])  # First peak name



except Exception as e:

    print("Error loading sample data:", str(e))


# ocr_matrix = np.load('../outputs/aitac/motifs/OCR_matrix.npy')
# print(ocr_matrix)

one_hot_seqs shape: (85, 4, 250)
cell_type_array shape: (85, 81)
peak_names shape: (85,)

Sample of one_hot_seqs (first sequence): [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0
  1 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0
  1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0
  1 1 0 0 0 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0
  0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 1
  0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 

In [88]:
pred =  list('''119.30222   212.46016   257.33496   308.04126   269.6403    191.52774
   20.540316 -150.35196  -120.5622    240.24734   299.8707    195.5897
  188.74388   282.49976   207.2959    215.4158    155.00168    52.021072
  -65.854645  -15.159489  -11.277153 -140.1776   -117.745544  -75.88133
 -116.79756   -62.25822   -64.65137   127.642365  199.37941    90.1638
   72.01878    74.005066  270.90884   -36.020164   81.49323   -17.63489
    2.934514  119.537224  173.21265   -86.28469   -66.30246   -96.82457
  -97.583084  -94.16221   -89.73187  -131.32265  -158.05948  -124.401505
 -147.17143   -43.548485 -140.81853  -187.2369   -191.25139  -182.74174
 -166.45482  -162.73163  -176.62598  -214.26643  -182.65182  -141.17429
 -147.66222  -131.25539  -148.40793  -124.78852  -154.63123  -106.300545
 -147.80756  -122.586845 -172.49455  -126.69004  -149.48738  -109.76181
 -175.42775  -113.66718    -7.420275  -63.831245 -142.46419  -162.34106
   51.966053   83.984604  117.898186'''.split(" "))

pred = [float(x) for x in pred if x]

tru = list('''1.151828 1.605631 1.727072 2.665989 3.523474 1.858122 1.373942 1.101284
 1.692156 1.416678 1.233521 2.4296   1.687405 1.417435 1.373942 1.703204
 1.580527 1.29398  1.086789 1.278626 1.085566 1.635836 1.559985 1.506694
 1.368486 1.17485  1.4463   1.36636  1.093838 1.640876 1.093838 1.52303
 1.090893 1.095567 1.475017 1.465835 1.747995 1.482109 1.090893 1.242042
 1.729853 1.531852 1.192144 1.525959 1.131276 1.708476 1.852317 1.373942
 1.608637 1.21101  1.185716 1.207718 1.667046 1.377415 1.249117 1.543197
 1.249231 1.51819  1.384767 2.146631 1.589669 1.764902 1.31831  1.449058
 1.249117 1.119638 1.240047 1.095567 1.086789 1.123134 1.407541 1.136541
 1.516218 1.743399 1.417632 1.093838 1.500516 1.088865 1.216065 1.192439
 1.43034'''.split(" "))

tru = [float(x) for x in tru if x]

pred = np.array([pred])
tru = np.array([tru])

ranked_indices = np.argsort(pred[::-1])  # Highest to lowest
ranked_tru = np.argsort(tru[::-1])
print("Top sequences for B cells:", ranked_indices[:10])
print(ranked_tru)


ranked_indices = ranked_indices.tolist()[0]
ranked_tru = ranked_tru.tolist()[0]
print(sorted(ranked_indices[:40]))
print(sorted(ranked_tru[:40]))
a =set(ranked_indices[:40]).intersection(set(ranked_tru[:40]))
print(len(a))




Top sequences for B cells: [[57 52 51 53 58 56 72 68 54 55 77 46 64  7 70 62 66 60 48 76 59 50 21 45
  61 69 63 47 67  8 22 24 73 71 65 42 41 43 44 39 23 40 18 26 75 25 49 33
  35 19 20 74 36  6 78 17 30 31 34 79 29 80  0 37 27 16 38 12  5 11 28 14
   1 15  9  2  4 32 13 10  3]]
[[20 18 68 77 38 32 75 30 28 33 67  7 65 69 44 71  0 25 50 42 79 51 49 78
  10 66 39 64 54 56 19 17 62 27 24  6 47 14 53 58 70  9 13 74 80 26 63 35
  34 37 76 23 72 57 31 43 41 55 22 16 60  1 48 21 29 52 12  8 15 45  2 40
  73 36 61 46  5 59 11  3  4]]
[7, 8, 21, 22, 24, 39, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 76, 77]
[0, 6, 7, 10, 14, 17, 18, 19, 20, 24, 25, 27, 28, 30, 32, 33, 38, 39, 42, 44, 47, 49, 50, 51, 53, 54, 56, 58, 62, 64, 65, 66, 67, 68, 69, 71, 75, 77, 78, 79]
21


In [158]:
# !pip install Bio

from Bio import SeqIO
import numpy as np

def one_hot_encode(sequence, seq_len):
    """
    Converts a DNA sequence to a one-hot encoded matrix.
    Args:
        sequence (str): Input DNA sequence (A, C, G, T).
        seq_len (int): Desired length for the sequence.
    Returns:
        np.ndarray: One-hot encoded matrix of shape (4, seq_len).
    """
    # Define mapping for one-hot encoding
    mapping = {'A': [1, 0, 0, 0], 'T': [0, 1, 0, 0], 'G': [0, 0, 1, 0], 'C': [0, 0, 0, 1]}

    # Pad or truncate the sequence to the desired length
    sequence = sequence.upper()
    if len(sequence) > seq_len:
        sequence = sequence[:seq_len]  # Truncate


    # Convert the sequence into a one-hot encoded matrix
    one_hot = np.array([mapping[base.upper()] for base in sequence])
    return one_hot.T  # Transpose to get shape (4, seq_len)

# Parameters
fasta_file = "../pax5_sequences_251.fa"  # Replace with your FASTA file
seq_len = 251  # Desired sequence length
output_file = "../one_hot_seqs_pax5.npy"

# Read sequences from the FASTA file and encode
one_hot_sequences = []
for record in SeqIO.parse(fasta_file, "fasta"):
    one_hot = one_hot_encode(str(record.seq), seq_len)
    one_hot_sequences.append(one_hot)

# Convert to a NumPy array with shape (n_sequences, 4, seq_len)
one_hot_array = np.array(one_hot_sequences)
print("Shape of one-hot encoded array:", one_hot_array.shape)

# Save the array to an .npy file
np.save(output_file, one_hot_array)
print(f"One-hot encoded sequences saved to {output_file}")


Shape of one-hot encoded array: (85, 4, 251)
One-hot encoded sequences saved to ../one_hot_seqs_pax5.npy


In [139]:
import numpy as np
import pandas as pd


one_hot_seqs_pax5 = "../one_hot_seqs_pax5.npy"
seqs_pax5 = np.load(one_hot_seqs_pax5)
print(seqs_pax5)

n_sequences = 85  # Number of sequences
n_cell_types = 81  # Number of cell types
dummy_labels = np.zeros((n_sequences, n_cell_types), dtype=np.float32)

output_file = "../dummy_labels.npy"
np.save(output_file, dummy_labels)

ids = pd.read_csv("../pax5_peaks_ids.txt", header=None).squeeze("columns")
ids = ids.to_numpy()
np.save("../peak_names_pax5.npy", ids, allow_pickle=True)
print(ids)




[[[0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [1 1 0 ... 1 0 0]
  [0 0 0 ... 0 1 1]]

 [[0 0 0 ... 0 1 0]
  [0 1 0 ... 0 0 1]
  [0 0 0 ... 1 0 0]
  [1 0 1 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [1 0 1 ... 0 1 0]
  [0 1 0 ... 0 0 0]
  [0 0 0 ... 1 0 1]]

 ...

 [[0 0 1 ... 0 0 0]
  [0 1 0 ... 1 0 1]
  [1 0 0 ... 0 0 0]
  [0 0 0 ... 0 1 0]]

 [[0 0 0 ... 0 1 0]
  [1 0 1 ... 0 0 1]
  [0 1 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]]

 [[0 0 0 ... 0 0 1]
  [1 1 0 ... 0 1 0]
  [0 0 1 ... 1 0 0]
  [0 0 0 ... 0 0 0]]]
['Peak_20' 'Peak_70' 'Peak_244' 'Peak_288' 'Peak_913' 'Peak_941'
 'Peak_1522' 'Peak_1898' 'Peak_1940' 'Peak_2217' 'Peak_2246' 'Peak_2429'
 'Peak_3184' 'Peak_3311' 'Peak_3566' 'Peak_3641' 'Peak_4138' 'Peak_4309'
 'Peak_4327' 'Peak_4697' 'Peak_4744' 'Peak_4998' 'Peak_5112' 'Peak_5443'
 'Peak_6443' 'Peak_6897' 'Peak_7059' 'Peak_7371' 'Peak_7409' 'Peak_7555'
 'Peak_7823' 'Peak_8588' 'Peak_8726' 'Peak_8745' 'Peak_8895' 'Peak_9086'
 'Peak_9154' 'Peak_9889' 'Peak_9945' 'Peak_10048' 'Peak_10115'
 'Peak_10

['Peak_20' 'Peak_70' 'Peak_244' 'Peak_288' 'Peak_913' 'Peak_941'
 'Peak_1522' 'Peak_1898' 'Peak_1940' 'Peak_2217' 'Peak_2246' 'Peak_2429'
 'Peak_3184' 'Peak_3311' 'Peak_3566' 'Peak_3641' 'Peak_4138' 'Peak_4309'
 'Peak_4327' 'Peak_4697' 'Peak_4744' 'Peak_4998' 'Peak_5112' 'Peak_5443'
 'Peak_6443' 'Peak_6897' 'Peak_7059' 'Peak_7371' 'Peak_7409' 'Peak_7555'
 'Peak_7823' 'Peak_8588' 'Peak_8726' 'Peak_8745' 'Peak_8895' 'Peak_9086'
 'Peak_9154' 'Peak_9889' 'Peak_9945' 'Peak_10048' 'Peak_10115'
 'Peak_10123' 'Peak_10735' 'Peak_11074' 'Peak_11259' 'Peak_11377'
 'Peak_11419' 'Peak_11453' 'Peak_11507' 'Peak_11680' 'Peak_11806'
 'Peak_12147' 'Peak_12637' 'Peak_13170' 'Peak_13197' 'Peak_13215'
 'Peak_13779' 'Peak_13802' 'Peak_14079' 'Peak_14353' 'Peak_14452'
 'Peak_15755' 'Peak_16217' 'Peak_16407' 'Peak_16636' 'Peak_16676'
 'Peak_17266' 'Peak_18225' 'Peak_18632' 'Peak_18886' 'Peak_19178'
 'Peak_19548' 'Peak_19744' 'Peak_19932' 'Peak_20365' 'Peak_21722'
 'Peak_21776' 'Peak_22553' 'Peak_22892' 'Peak

In [159]:
!python -u extract_motifs.py 'aitac' '../one_hot_seqs_pax5.npy' '../target_heights_Pax5.npy' '../peak_names_pax5.npy'

/content/AI-TAC/code/extract_motifs.py:43: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load('../models/' + model_name + '.ckpt', map_location= torch.dev